{% set name = "scikit-mobility" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e4c4a229044953c5740c31f1f9b38df01420f595d11c22c9d106845d6b5e1d3

build:
  number: 0
  # missing h3-py, python-igraph for 3.12
  skip: True  # [py<38 or py>311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    # - fiona
    - folium >=0.12.1.post1
    - geojson >=2.5.0
    - geopandas >=0.10.2
    # - matplotlib-base
    # - numpy
    - pandas >=1.1.5
    - powerlaw >=1.4.6
    # - python
    - requests >=2.25.1
    # - rtree
    - scikit-learn
    # - scipy
    # - shapely
    - statsmodels >=0.13.0
    - tqdm >=4.60.0
    - python-igraph >=0.9.1
    - h3-py >=3.7.3
    # - pyproj
    - pooch >=1.6.0
    - python

test:
  source_files:
    - skmob/core/tests
    - skmob/data/tests
    - skmob/io/tests
    - skmob/measures/tests
    - skmob/models/tests
    - skmob/preprocessing/tests
    - skmob/privacy/tests
    - skmob/tessellation/tests
    - skmob/utils/tests
  imports:
    - skmob
    - skmob.core
    - skmob.io
    - skmob.measures
    - skmob.models
    - skmob.preprocessing
    - skmob.privacy
    - skmob.tessellation
    - skmob.utils
  commands:
    # - pip check
    - cd skmob
    - cd core
    - pytest -vv tests
    # - pytest -vv core/tests
    # - pytest -vv data/tests
    # - pytest -vv io/tests
    # - pytest -vv measures/tests
    # - pytest -vv models/tests
    # - pytest -vv preprocessing/tests
    # - pytest -vv privacy/tests
    # - pytest -vv tessellation/tests
    # - pytest -vv utils/tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/scikit-mobility/scikit-mobility
  dev_url: https://github.com/scikit-mobility/scikit-mobility
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A toolbox for analyzing and processing mobility data.
  description: |
    scikit-mobility is a library for human mobility analysis in Python. The library allows to: (i) represent trajectories and mobility flows with 
    proper data structures, TrajDataFrame and FlowDataFrame; (ii) manage and manipulate mobility data of various formats 
    (call detail records, GPS data, data from social media, survey data, etc.); (ii) extract mobility metrics and patterns from data, both at 
    individual and collective level (e.g., length of displacements, characteristic distance, origin-destination matrix, etc.); (iii) generate 
    synthetic individual trajectories using standard mathematical models (random walk models, exploration and preferential return model, etc.);
    (iv) generate synthetic mobility flows using standard migration models (gravity model, radiation model, etc.); (v) assess the privacy risk 
    associated with a mobility data set.
  doc_url: https://github.com/scikit-mobility/scikit-mobility

extra:
  recipe-maintainers:
    - gbarlacchi
    - jonpappalord
    - pellungrobe
    - FilippoSimini
